version: '3'

services:
  anchor-service:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    env_file:
     - ./environment.dev
    command: npm start
